export enum EntityFromSystemType {
  APPOINTMENTS = 'APPOINTMENTS',
  AUTH = 'AUTH',
  CORE = 'CORE',
  ENTITY_FROM_SYSTEM = 'ENTITY_FROM_SYSTEM',
  PERMISSIONS = 'PERMISSIONS',
  PRODUCTS = 'PRODUCTS',
  ROLES = 'ROLES',
  USERS = 'USERS',
  VEHICLES = 'VEHICLES',
}
